[project]
name = "ollama-modal"
version = "0.1.0"
description = "Ollama quickstart with Modal"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "modal>=0.73.51",
    "ruff>=0.9.6",
]
